spring.application.name=Edustream

# postgres
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.aspfkaueneodwysbwzss
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate (jpa)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#  Spring Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=22130108@st.hcmuaf.edu.vn
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Spring Security OAuth2

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# JWT
jwt.secret-key=${SECRET_KEY}
jwt.access-token-expiration=150000
jwt.refresh-token-expiration=604800000

#
app.fontend-domain=http://localhost:3000/oauth2/redirect

# server
server.port=8080